/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data interval
 */
export type AccountUsageStatisticsInterval = '1h' | '1d';

export const AccountUsageStatisticsInterval = {
    _1h: '1h' as AccountUsageStatisticsInterval,
    _1d: '1d' as AccountUsageStatisticsInterval
};

