/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiUsageDataTransfer } from './apiUsageDataTransfer';


/**
 * Usage history entry
 */
export interface ApiUsageEntry { 
    requests: number;
    data: ApiUsageDataTransfer;
}

