/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommodityTypeObj } from './commodityTypeObj';


/**
 * A list of commodity types
 */
export interface CommodityTypesList { 
    items: Array<CommodityTypeObj>;
}

