/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CommodityType = 'agricultural' | 'energy' | 'metal' | 'all';

export const CommodityType = {
    Agricultural: 'agricultural' as CommodityType,
    Energy: 'energy' as CommodityType,
    Metal: 'metal' as CommodityType,
    All: 'all' as CommodityType
};

