/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConversionQuery } from './conversionQuery';
import { ConversionInfo } from './conversionInfo';


export interface Conversion { 
    info: ConversionInfo;
    query: ConversionQuery;
    result: number;
}

