/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The country associated with the symbol (see ISO 3166-1 alpha-2)
 */
export type Country = 'fr' | 'us' | 'de' | 'nz' | 'nl' | 'uk' | 'es' | 'cn' | 'ch' | 'gr' | 'be' | 'pt' | 'it' | 'all';

export const Country = {
    Fr: 'fr' as Country,
    Us: 'us' as Country,
    De: 'de' as Country,
    Nz: 'nz' as Country,
    Nl: 'nl' as Country,
    Uk: 'uk' as Country,
    Es: 'es' as Country,
    Cn: 'cn' as Country,
    Ch: 'ch' as Country,
    Gr: 'gr' as Country,
    Be: 'be' as Country,
    Pt: 'pt' as Country,
    It: 'it' as Country,
    All: 'all' as Country
};

