/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CountryObj } from './countryObj';


/**
 * A list of Countries
 */
export interface CountriesList { 
    items: Array<CountryObj>;
}

