/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CryptoExchangeItem } from './cryptoExchangeItem';


/**
 * A list of cryptocurrency exchanges
 */
export interface CryptoExchangesList { 
    items: Array<CryptoExchangeItem>;
}

