/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConversionInfo } from './conversionInfo';
import { CryptoConversionQuery } from './cryptoConversionQuery';


export interface CryptoConversion { 
    info: ConversionInfo;
    query: CryptoConversionQuery;
    result: number;
}

