/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A cryptocurrency exchange
 */
export interface CryptoExchangeItem { 
    /**
     * Exchange identifier
     */
    id: string;
    /**
     * Exchange name
     */
    name: string;
    /**
     * Exchange established year
     */
    year_established: number;
}

