/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SymbolsOutFull } from './symbolsOutFull';


export interface CursorPageTCustomizedSymbolsOutFull { 
    items: Array<SymbolsOutFull>;
    total?: number | null;
    current_page?: string | null;
    current_page_backwards?: string | null;
    previous_page?: string | null;
    next_page?: string | null;
}

