/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LastQuote { 
    /**
     * Symbol name
     */
    symbol: string;
    /**
     * The ask price.
     */
    ask: number;
    /**
     * The bid price.
     */
    bid: number;
    /**
     * The mid price.
     */
    mid: number;
    timestamp: number;
}

