/**
 * tradewatch.io
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SymbolsListMode = 'full' | 'base';

export const SymbolsListMode = {
    Full: 'full' as SymbolsListMode,
    Base: 'base' as SymbolsListMode
};

